--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1 (Debian 13.1-1.pgdg100+1)
-- Dumped by pg_dump version 13.1 (Debian 13.1-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Billings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Billings" (
    "Id" integer NOT NULL,
    "BeneficiaryId" integer NOT NULL,
    "BeneficiaryName" text,
    "PersonType" integer NOT NULL,
    "EndDate" timestamp without time zone,
    "Price" numeric NOT NULL,
    "Discount" numeric,
    "IsPaid" boolean NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.316921+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.316977+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Billings" OWNER TO postgres;

--
-- Name: Billings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Billings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Billings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Category" (
    "Id" integer NOT NULL,
    "Name" text,
    "Description" text,
    "ShowOnHomepage" boolean NOT NULL,
    "ParentId" integer,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.391294+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.391341+00'::timestamp with time zone NOT NULL,
    "ProductTemplateId" integer
);


ALTER TABLE public."Category" OWNER TO postgres;

--
-- Name: Category_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Category" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Category_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MediaResource; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MediaResource" (
    "Id" integer NOT NULL,
    "Size" bigint NOT NULL,
    "Type" integer NOT NULL,
    "SourceUrl" text,
    "Caption" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.31273+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.312774+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."MediaResource" OWNER TO postgres;

--
-- Name: MediaResource_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MediaResource" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MediaResource_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: POSOrder; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."POSOrder" (
    "Id" integer NOT NULL,
    "DiscountTotal" numeric NOT NULL,
    "PaymentMethod" integer NOT NULL,
    "HasDealWithStore" boolean NOT NULL,
    "ConsumerCode" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.308184+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.308239+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."POSOrder" OWNER TO postgres;

--
-- Name: POSOrderItem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."POSOrderItem" (
    "Id" integer NOT NULL,
    "ProductUniqueCode" text,
    "ProductId" integer,
    "Quantity" integer NOT NULL,
    "CustomerValue" numeric NOT NULL,
    "CostPrice" numeric NOT NULL,
    "POSOrderId" integer NOT NULL,
    "POSOrderId1" integer,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.31226+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.312319+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."POSOrderItem" OWNER TO postgres;

--
-- Name: POSOrderItem_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."POSOrderItem" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."POSOrderItem_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: POSOrder_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."POSOrder" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."POSOrder_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Product" (
    "Id" integer NOT NULL,
    "BaseProductId" integer,
    "PrCdse" text,
    "ManufacturerId" integer,
    "ManufacturerName" text,
    "ManufacturerCountry" text,
    "CommercialName" text,
    "Classification" text,
    "RiskClass" character varying(3) NOT NULL,
    "Concentration" real,
    "FisicForm" character varying(256),
    "Dosage" text,
    "AbsoluteDosageInMg" double precision,
    "ActivePrinciple" text,
    "LotNumber" text,
    "PrescriptionNeeded" boolean NOT NULL,
    "UseRestriction" character varying(128) NOT NULL,
    "IsPriceFixed" boolean NOT NULL,
    "DigitalBuleLink" text,
    "LaboratoryCode" text,
    "LaboratoryName" text,
    "Ncm" text,
    "QuantityInStock" integer NOT NULL,
    "LastStockEntry" timestamp with time zone,
    "ReorderLevel" integer NOT NULL,
    "ReorderQuantity" integer NOT NULL,
    "EndCustomerPrice" numeric NOT NULL,
    "CostPrice" numeric NOT NULL,
    "SavingPercentage" numeric NOT NULL,
    "BarCode" text,
    "Description" text,
    "Section" text,
    "MaxDiscountPercentage" numeric NOT NULL,
    "DiscountValue" numeric NOT NULL,
    "Commission" text,
    "ICMS" numeric NOT NULL,
    "MinimumStock" integer NOT NULL,
    "MainSupplierName" text,
    "Name" text,
    "RegistryCode" text,
    "OwnerOfRegistry" text,
    "RegistryPublicationDate" timestamp without time zone,
    "DateOfRegistryUpdate" timestamp with time zone,
    "RegistryValidity" character varying(64),
    "MedicalProductModel" text,
    "Stripe" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.403772+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.403828+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Product" OWNER TO postgres;

--
-- Name: ProductCategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductCategory" (
    "Id" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.392431+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.392484+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductCategory" OWNER TO postgres;

--
-- Name: ProductCategory_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductCategory" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductCategory_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductMedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductMedia" (
    "Id" integer NOT NULL,
    "MediaResourceId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "IsThumbnail" boolean NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.40508+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.405138+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductMedia" OWNER TO postgres;

--
-- Name: ProductMedia_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductMedia" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductMedia_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductPrice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductPrice" (
    "Id" integer NOT NULL,
    "Pricestartdate" timestamp with time zone,
    "EndCustomerDrugPrice" numeric NOT NULL,
    "CostPrice" numeric NOT NULL,
    "ProductId" integer NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.40601+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.406059+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductPrice" OWNER TO postgres;

--
-- Name: ProductPrice_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductPrice" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductPrice_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductShelfLife; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductShelfLife" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "StockEntryId" integer NOT NULL,
    "StartDate" timestamp without time zone,
    "EndDate" timestamp without time zone,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.406522+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.406572+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductShelfLife" OWNER TO postgres;

--
-- Name: ProductShelfLife_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductShelfLife" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductShelfLife_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductStockEntry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductStockEntry" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "StockEntryId" integer NOT NULL,
    "ProductMaturityDate" timestamp without time zone,
    "Quantity" integer NOT NULL,
    "LotCode" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.407064+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.407112+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductStockEntry" OWNER TO postgres;

--
-- Name: ProductStockEntry_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductStockEntry" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductStockEntry_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductSupplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductSupplier" (
    "Id" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "SupplierId" integer NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.407944+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.407995+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductSupplier" OWNER TO postgres;

--
-- Name: ProductSupplier_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductSupplier" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductSupplier_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductTax; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductTax" (
    "Id" integer NOT NULL,
    "TaxId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2021-01-13 22:26:48.987304+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2021-01-13 22:26:48.987357+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductTax" OWNER TO postgres;

--
-- Name: ProductTax_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductTax" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductTax_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductTemplate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ProductTemplate" (
    "Id" integer NOT NULL,
    "Name" text,
    "CommercialName" text,
    "ManufacturerName" text,
    "ManufacturerCountry" text,
    "OwnerOfRegistry" text,
    "RegistryCode" text,
    "RegistryPublicationDate" timestamp without time zone NOT NULL,
    "DateOfRegistryUpdate" timestamp with time zone NOT NULL,
    "RegistryValidity" text,
    "MedicalProductModel" text,
    "Classification" text,
    "RiskClass" integer NOT NULL,
    "ActivePrinciple" text,
    "Concentration" text,
    "FisicForm" text,
    "UseRestriction" text,
    "PrescriptionNeeded" boolean NOT NULL,
    "Stripe" integer NOT NULL,
    "IsPricedFixed" boolean NOT NULL,
    "LaboratoryName" text,
    "EndCustomerPrice" numeric NOT NULL,
    "CostPrice" numeric NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2021-01-13 22:26:48.994586+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2021-01-13 22:26:48.994637+00'::timestamp with time zone NOT NULL,
    "CategoriesIds" integer[] NOT NULL,
    "TaxesIds" integer[]
);


ALTER TABLE public."ProductTemplate" OWNER TO postgres;

--
-- Name: ProductTemplate_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ProductTemplate" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductTemplate_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Products_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Product" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Products_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: StockChange; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."StockChange" (
    "Id" integer NOT NULL,
    "ImpactingEntityId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Type" integer NOT NULL,
    "Note" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.407064+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.407112+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."StockChange" OWNER TO postgres;

--
-- Name: StockChange_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."StockChange" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StockChange_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: StockEntry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."StockEntry" (
    "Id" integer NOT NULL,
    "NfNumber" text,
    "NfEmissionDate" timestamp without time zone,
    "Totalcost" numeric,
    "SupplierId" integer,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.291622+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.291691+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."StockEntry" OWNER TO postgres;

--
-- Name: StockEntry_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."StockEntry" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StockEntry_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Supplier" (
    "Id" integer NOT NULL,
    "AddressId" integer,
    "Name" text,
    "Cnpj" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.298688+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.298759+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Supplier" OWNER TO postgres;

--
-- Name: Supplier_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Supplier" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Supplier_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Syncronization; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Syncronization" (
    "Id" integer NOT NULL,
    "UpdatedFrom" text,
    "LastSyncronization" timestamp with time zone NOT NULL,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.034872+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.046775+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Syncronization" OWNER TO postgres;

--
-- Name: Syncronization_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Syncronization" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Syncronization_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Taxes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Taxes" (
    "Id" integer NOT NULL,
    "Name" text,
    "Percentage" numeric NOT NULL,
    "ProductTemplateId" integer,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2021-01-13 22:26:48.961497+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2021-01-13 22:26:48.96154+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public."Taxes" OWNER TO postgres;

--
-- Name: Taxes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Taxes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Taxes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.addresses (
    "Id" integer NOT NULL,
    "FirstAddressLine" text,
    "SecondAddressLine" text,
    "Zipcode" text,
    "Addressnumber" text,
    "City" text,
    "AddressState" text,
    "District" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.321036+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.321122+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public.addresses OWNER TO postgres;

--
-- Name: addresses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.addresses ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."addresses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: beneficiaries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.beneficiaries (
    "Id" integer NOT NULL,
    "Name" text,
    "AddressId" integer NOT NULL,
    "Discriminator" text NOT NULL,
    "Cpf" character varying(12),
    "Cnpj" text,
    "UniqueCode" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT '2020-12-09 20:59:45.390661+00'::timestamp with time zone NOT NULL,
    "LastUpdatedOn" timestamp with time zone DEFAULT '2020-12-09 20:59:45.390726+00'::timestamp with time zone NOT NULL
);


ALTER TABLE public.beneficiaries OWNER TO postgres;

--
-- Name: beneficiaries_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.beneficiaries ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."beneficiaries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



--
-- Data for Name: ProductCategory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductCategory" ("Id", "CategoryId", "ProductId", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: ProductMedia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductMedia" ("Id", "MediaResourceId", "ProductId", "IsThumbnail", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: ProductPrice; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductPrice" ("Id", "Pricestartdate", "EndCustomerDrugPrice", "CostPrice", "ProductId", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: ProductShelfLife; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductShelfLife" ("Id", "ProductId", "StockEntryId", "StartDate", "EndDate", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: ProductStockEntry; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductStockEntry" ("Id", "ProductId", "StockEntryId", "ProductMaturityDate", "Quantity", "LotCode", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: ProductSupplier; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductSupplier" ("Id", "ProductId", "SupplierId", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: ProductTax; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductTax" ("Id", "TaxId", "ProductId", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: ProductTemplate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ProductTemplate" ("Id", "Name", "CommercialName", "ManufacturerName", "ManufacturerCountry", "OwnerOfRegistry", "RegistryCode", "RegistryPublicationDate", "DateOfRegistryUpdate", "RegistryValidity", "MedicalProductModel", "Classification", "RiskClass", "ActivePrinciple", "Concentration", "FisicForm", "UseRestriction", "PrescriptionNeeded", "Stripe", "IsPricedFixed", "LaboratoryName", "EndCustomerPrice", "CostPrice", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn", "CategoriesIds", "TaxesIds") FROM stdin;
\.


--
-- Data for Name: StockChange; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."StockChange" ("Id", "ImpactingEntityId", "ProductId", "Quantity", "Type", "Note", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: StockEntry; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."StockEntry" ("Id", "NfNumber", "NfEmissionDate", "Totalcost", "SupplierId", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: Supplier; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Supplier" ("Id", "AddressId", "Name", "Cnpj", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: Syncronization; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Syncronization" ("Id", "UpdatedFrom", "LastSyncronization", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: Taxes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Taxes" ("Id", "Name", "Percentage", "ProductTemplateId", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20201209205945_BaseCreate	5.0.0-rc.1.20451.13
20210113222649_AddingMoreEntities	5.0.0-rc.1.20451.13
20210125210723_RemovingRelationsFromProductTemplate	5.0.0-rc.1.20451.13
\.


--
-- Data for Name: addresses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.addresses ("Id", "FirstAddressLine", "SecondAddressLine", "Zipcode", "Addressnumber", "City", "AddressState", "District", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Data for Name: beneficiaries; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.beneficiaries ("Id", "Name", "AddressId", "Discriminator", "Cpf", "Cnpj", "UniqueCode", "IsDeleted", "CreatedAt", "LastUpdatedOn") FROM stdin;
\.


--
-- Name: Billings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Billings_Id_seq"', 1, false);


--
-- Name: Category_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Category_Id_seq"', 1, false);


--
-- Name: MediaResource_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MediaResource_Id_seq"', 1, false);


--
-- Name: POSOrderItem_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."POSOrderItem_Id_seq"', 1, false);


--
-- Name: POSOrder_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."POSOrder_Id_seq"', 1, false);


--
-- Name: ProductCategory_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductCategory_Id_seq"', 1, false);


--
-- Name: ProductMedia_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductMedia_Id_seq"', 1, false);


--
-- Name: ProductPrice_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductPrice_Id_seq"', 1, false);


--
-- Name: ProductShelfLife_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductShelfLife_Id_seq"', 1, false);


--
-- Name: ProductStockEntry_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductStockEntry_Id_seq"', 1, false);


--
-- Name: ProductSupplier_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductSupplier_Id_seq"', 1, false);


--
-- Name: ProductTax_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductTax_Id_seq"', 1, false);


--
-- Name: ProductTemplate_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ProductTemplate_Id_seq"', 1, false);


--
-- Name: Products_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Products_Id_seq"', 151952, true);


--
-- Name: StockChange_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."StockChange_Id_seq"', 1, false);


--
-- Name: StockEntry_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."StockEntry_Id_seq"', 1, false);


--
-- Name: Supplier_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Supplier_Id_seq"', 1, false);


--
-- Name: Syncronization_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Syncronization_Id_seq"', 1, false);


--
-- Name: Taxes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Taxes_Id_seq"', 1, false);


--
-- Name: addresses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."addresses_Id_seq"', 1, false);


--
-- Name: beneficiaries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."beneficiaries_Id_seq"', 1, false);


--
-- Name: Billings PK_Billings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Billings"
    ADD CONSTRAINT "PK_Billings" PRIMARY KEY ("Id");


--
-- Name: Category PK_Category; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "PK_Category" PRIMARY KEY ("Id");


--
-- Name: MediaResource PK_MediaResource; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaResource"
    ADD CONSTRAINT "PK_MediaResource" PRIMARY KEY ("Id");


--
-- Name: POSOrder PK_POSOrder; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."POSOrder"
    ADD CONSTRAINT "PK_POSOrder" PRIMARY KEY ("Id");


--
-- Name: POSOrderItem PK_POSOrderItem; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."POSOrderItem"
    ADD CONSTRAINT "PK_POSOrderItem" PRIMARY KEY ("Id");


--
-- Name: ProductCategory PK_ProductCategory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductCategory"
    ADD CONSTRAINT "PK_ProductCategory" PRIMARY KEY ("Id");


--
-- Name: ProductMedia PK_ProductMedia; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductMedia"
    ADD CONSTRAINT "PK_ProductMedia" PRIMARY KEY ("Id");


--
-- Name: ProductPrice PK_ProductPrice; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductPrice"
    ADD CONSTRAINT "PK_ProductPrice" PRIMARY KEY ("Id");


--
-- Name: ProductShelfLife PK_ProductShelfLife; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductShelfLife"
    ADD CONSTRAINT "PK_ProductShelfLife" PRIMARY KEY ("Id");


--
-- Name: ProductStockEntry PK_ProductStockEntry; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductStockEntry"
    ADD CONSTRAINT "PK_ProductStockEntry" PRIMARY KEY ("Id");


--
-- Name: ProductSupplier PK_ProductSupplier; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductSupplier"
    ADD CONSTRAINT "PK_ProductSupplier" PRIMARY KEY ("Id");


--
-- Name: ProductTax PK_ProductTax; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductTax"
    ADD CONSTRAINT "PK_ProductTax" PRIMARY KEY ("Id");


--
-- Name: ProductTemplate PK_ProductTemplate; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductTemplate"
    ADD CONSTRAINT "PK_ProductTemplate" PRIMARY KEY ("Id");


--
-- Name: Product PK_Products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "PK_Products" PRIMARY KEY ("Id");


--
-- Name: StockChange PK_StockChange; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."StockChange"
    ADD CONSTRAINT "PK_StockChange" PRIMARY KEY ("Id");


--
-- Name: StockEntry PK_StockEntry; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."StockEntry"
    ADD CONSTRAINT "PK_StockEntry" PRIMARY KEY ("Id");


--
-- Name: Supplier PK_Supplier; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Supplier"
    ADD CONSTRAINT "PK_Supplier" PRIMARY KEY ("Id");


--
-- Name: Syncronization PK_Syncronization; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Syncronization"
    ADD CONSTRAINT "PK_Syncronization" PRIMARY KEY ("Id");


--
-- Name: Taxes PK_Taxes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Taxes"
    ADD CONSTRAINT "PK_Taxes" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: addresses PK_addresses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT "PK_addresses" PRIMARY KEY ("Id");


--
-- Name: beneficiaries PK_beneficiaries; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beneficiaries
    ADD CONSTRAINT "PK_beneficiaries" PRIMARY KEY ("Id");


--
-- Name: IX_Category_ParentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Category_ParentId" ON public."Category" USING btree ("ParentId");


--
-- Name: IX_Category_ProductTemplateId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Category_ProductTemplateId" ON public."Category" USING btree ("ProductTemplateId");


--
-- Name: IX_POSOrderItem_POSOrderId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_POSOrderItem_POSOrderId" ON public."POSOrderItem" USING btree ("POSOrderId");


--
-- Name: IX_POSOrderItem_POSOrderId1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_POSOrderItem_POSOrderId1" ON public."POSOrderItem" USING btree ("POSOrderId1");


--
-- Name: IX_POSOrderItem_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_POSOrderItem_ProductId" ON public."POSOrderItem" USING btree ("ProductId");


--
-- Name: IX_ProductCategory_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductCategory_CategoryId" ON public."ProductCategory" USING btree ("CategoryId");


--
-- Name: IX_ProductCategory_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductCategory_ProductId" ON public."ProductCategory" USING btree ("ProductId");


--
-- Name: IX_ProductMedia_MediaResourceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductMedia_MediaResourceId" ON public."ProductMedia" USING btree ("MediaResourceId");


--
-- Name: IX_ProductMedia_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductMedia_ProductId" ON public."ProductMedia" USING btree ("ProductId");


--
-- Name: IX_ProductPrice_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductPrice_ProductId" ON public."ProductPrice" USING btree ("ProductId");


--
-- Name: IX_ProductShelfLife_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductShelfLife_ProductId" ON public."ProductShelfLife" USING btree ("ProductId");


--
-- Name: IX_ProductStockEntry_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductStockEntry_ProductId" ON public."ProductStockEntry" USING btree ("ProductId");


--
-- Name: IX_ProductStockEntry_StockEntryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductStockEntry_StockEntryId" ON public."ProductStockEntry" USING btree ("StockEntryId");


--
-- Name: IX_ProductSupplier_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductSupplier_ProductId" ON public."ProductSupplier" USING btree ("ProductId");


--
-- Name: IX_ProductSupplier_SupplierId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductSupplier_SupplierId" ON public."ProductSupplier" USING btree ("SupplierId");


--
-- Name: IX_ProductTax_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductTax_ProductId" ON public."ProductTax" USING btree ("ProductId");


--
-- Name: IX_ProductTax_TaxId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ProductTax_TaxId" ON public."ProductTax" USING btree ("TaxId");


--
-- Name: IX_StockChange_ProductId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_StockChange_ProductId" ON public."StockChange" USING btree ("ProductId");


--
-- Name: IX_StockEntry_SupplierId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_StockEntry_SupplierId" ON public."StockEntry" USING btree ("SupplierId");


--
-- Name: IX_Supplier_AddressId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Supplier_AddressId" ON public."Supplier" USING btree ("AddressId");


--
-- Name: IX_Taxes_ProductTemplateId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Taxes_ProductTemplateId" ON public."Taxes" USING btree ("ProductTemplateId");


--
-- Name: IX_beneficiaries_AddressId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_beneficiaries_AddressId" ON public.beneficiaries USING btree ("AddressId");


--
-- Name: Category FK_Category_Category_ParentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "FK_Category_Category_ParentId" FOREIGN KEY ("ParentId") REFERENCES public."Category"("Id") ON DELETE CASCADE;


--
-- Name: Category FK_Category_ProductTemplate_ProductTemplateId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "FK_Category_ProductTemplate_ProductTemplateId" FOREIGN KEY ("ProductTemplateId") REFERENCES public."ProductTemplate"("Id") ON DELETE CASCADE;


--
-- Name: POSOrderItem FK_POSOrderItem_POSOrder_POSOrderId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."POSOrderItem"
    ADD CONSTRAINT "FK_POSOrderItem_POSOrder_POSOrderId" FOREIGN KEY ("POSOrderId") REFERENCES public."POSOrder"("Id") ON DELETE CASCADE;


--
-- Name: POSOrderItem FK_POSOrderItem_POSOrder_POSOrderId1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."POSOrderItem"
    ADD CONSTRAINT "FK_POSOrderItem_POSOrder_POSOrderId1" FOREIGN KEY ("POSOrderId1") REFERENCES public."POSOrder"("Id") ON DELETE RESTRICT;


--
-- Name: POSOrderItem FK_POSOrderItem_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."POSOrderItem"
    ADD CONSTRAINT "FK_POSOrderItem_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE RESTRICT;


--
-- Name: ProductCategory FK_ProductCategory_Category_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductCategory"
    ADD CONSTRAINT "FK_ProductCategory_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Category"("Id") ON DELETE RESTRICT;


--
-- Name: ProductCategory FK_ProductCategory_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductCategory"
    ADD CONSTRAINT "FK_ProductCategory_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: ProductMedia FK_ProductMedia_MediaResource_MediaResourceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductMedia"
    ADD CONSTRAINT "FK_ProductMedia_MediaResource_MediaResourceId" FOREIGN KEY ("MediaResourceId") REFERENCES public."MediaResource"("Id") ON DELETE RESTRICT;


--
-- Name: ProductMedia FK_ProductMedia_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductMedia"
    ADD CONSTRAINT "FK_ProductMedia_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: ProductPrice FK_ProductPrice_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductPrice"
    ADD CONSTRAINT "FK_ProductPrice_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: ProductShelfLife FK_ProductShelfLife_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductShelfLife"
    ADD CONSTRAINT "FK_ProductShelfLife_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: ProductStockEntry FK_ProductStockEntry_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductStockEntry"
    ADD CONSTRAINT "FK_ProductStockEntry_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: ProductStockEntry FK_ProductStockEntry_StockEntry_StockEntryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductStockEntry"
    ADD CONSTRAINT "FK_ProductStockEntry_StockEntry_StockEntryId" FOREIGN KEY ("StockEntryId") REFERENCES public."StockEntry"("Id") ON DELETE CASCADE;


--
-- Name: ProductSupplier FK_ProductSupplier_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductSupplier"
    ADD CONSTRAINT "FK_ProductSupplier_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: ProductSupplier FK_ProductSupplier_Supplier_SupplierId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductSupplier"
    ADD CONSTRAINT "FK_ProductSupplier_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES public."Supplier"("Id") ON DELETE RESTRICT;


--
-- Name: ProductTax FK_ProductTax_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductTax"
    ADD CONSTRAINT "FK_ProductTax_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: ProductTax FK_ProductTax_Taxes_TaxId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ProductTax"
    ADD CONSTRAINT "FK_ProductTax_Taxes_TaxId" FOREIGN KEY ("TaxId") REFERENCES public."Taxes"("Id") ON DELETE CASCADE;


--
-- Name: StockChange FK_StockChange_Products_ProductId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."StockChange"
    ADD CONSTRAINT "FK_StockChange_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES public."Product"("Id") ON DELETE CASCADE;


--
-- Name: StockEntry FK_StockEntry_Supplier_SupplierId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."StockEntry"
    ADD CONSTRAINT "FK_StockEntry_Supplier_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES public."Supplier"("Id") ON DELETE RESTRICT;


--
-- Name: Supplier FK_Supplier_addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Supplier"
    ADD CONSTRAINT "FK_Supplier_addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES public.addresses("Id") ON DELETE RESTRICT;


--
-- Name: Taxes FK_Taxes_ProductTemplate_ProductTemplateId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Taxes"
    ADD CONSTRAINT "FK_Taxes_ProductTemplate_ProductTemplateId" FOREIGN KEY ("ProductTemplateId") REFERENCES public."ProductTemplate"("Id") ON DELETE CASCADE;


--
-- Name: beneficiaries FK_beneficiaries_addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beneficiaries
    ADD CONSTRAINT "FK_beneficiaries_addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES public.addresses("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--